# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A blockwise loop implementation for computing x'Ay using Rcpp
#'
#' This function computes x'Ay using blockwise nested loop using Rcpp
#' @param x A size n vector
#' @param y A size m vector
#' @param A A size (n x m) matrix
#' @param blkSize The size of blocks (in #rows or #cols) in calculating x'Ay
#' @return A scalar value evaluating x'Ay
quadsumB <- function(x, y, A, blkSize) {
    .Call(`_quadsum815_quadsumB`, x, y, A, blkSize)
}

#' A loop-based Rcpp implementation for computing x'Ay
#'
#' @param x A size n vector
#' @param y A size m vector
#' @param A A size (n x m) matrix
#' @return A scalar value evaluating x'Ay
quadsumC <- function(x, y, A) {
    .Call(`_quadsum815_quadsumC`, x, y, A)
}

